### PR TITLE
optimized flood fill algorithm

### PR DESCRIPTION
**Pull request by rhysdh540**
15 billion `IntPoint` allocations begone

### CODE REVIEW

**Comment by Obscure2020** [comment]
This is a promising PR! I'd like you to make a few changes before I merge it.
1. Four-spaces indents please. I realize I don't have a written or public style guide on how I format my stuff, so I'm telling you here. In future I'll make that more explicitly-announced somewhere.
    - For instance, I'll accept your de-nesting of my children-handling code in the constructor of `Island` if you un-frick the indenting.
    - If the body of an `if` statement is only one line, and that line is brief, I prefer that the `if` statement be written in-line. So use this:
        ```java
        if(!canHaveChildren) return;
        ```
        ...instead of this:
        ```java
        if(!canHaveChildren){
            return;
        }
        ```
2. I don't want to have to pass a capacity into the IntQueue constructor, nor do I want `add()` to throw an exception. Make the following changes to IntQueue:
    - The constructor takes no arguments, and creates a backing array of length 64.
    - The backing array is no longer `final`.
    - There shall be no one-element `add()` and a two-element `add()`. There shall be one public-facing `add()`, that takes in a variable number of arguments, and its implementation should just iterate through its arguments and pass them one-by-one to `internalAdd()`, which is the current one-element `add()` but renamed and changed to `private`.
    - `internalAdd()` should check if the tail is at the head *before* storing a new element, not after. If it detects that the tail is indeed at the head, a new array should be allocated, with its new length being `arr.length + (arr.length >> 1)`. Then all the elements of the previous array, starting at `head` and ending at `tail` are to be copied into the new array. `arr` is then replaced with our new array, `head` is now replaced with 0, and `tail` is now replaced with the previous `arr` capacity plus one. Then the new item that got passed in is finally inserted at the tail, and then tail is `wrapIncrement()`-ed.
    - I don't like modifying variables inside of `if` statements. That means any usages of the `=` operator or the `++` operator should be moved to separate lines *prior* to the `if` statements in which the variables are compared with other values.

**Comment by rhysdh540** [comment]
I've gone ahead and made the style changes you asked for. However, I have some concerns about your proposed changes to `IntQueue`. I understand that you want to reduce the amount of memory used, and your changes are reasonable. One thing I'm concerned about, however, is using varargs in method parameters, since this is equivalent to constructing an array and calling the method with that, which is both slow and memory-inefficient. I'd rather keep the 1-and-2 thing going on already, or just using one `add` method with 1 parameter.

**Comment by Obscure2020** [comment]
You know what, I agree with you. For this project it would be more efficient to avoid varargs. I can easily add varargs support myself if I ever need it in the future. For the time being, let's keep the `add(int)` and the `add(int,int)`. Here's the rewritten, reconsidered list of changes I'd still like to see in `IntQueue`:
1. The constructor takes no arguments, and creates a initial backing array of length 64.
1. The backing array is no longer `final`.
1. The single-argument `add()` should check if the tail is at the head *before* storing a new element, not after. If it detects that the tail is indeed at the head, a new array should be allocated, with its new length being `arr.length + (arr.length >> 1)`. Then all the elements of the previous array, starting at `head` and ending at `tail` are to be copied into the new array. `arr` is then replaced with our new array, `head` is now replaced with 0, and `tail` is now replaced with the previous `arr` capacity plus one. Then the new item that got passed in is finally inserted at the tail, and then tail is `wrapIncrement()`-ed.

**Comment by Obscure2020** [comment]
This is closer to what I had wanted, but I still take issue with your implementation of the growable `IntQueue`. I don't like "outlawing" a specific integer value (in this case, `Integer.MIN_VALUE`) by making it a sort of sentinel... I would rather waste one int-worth of memory and keep the `IntQueue` amicable to all possible int values. I have a new idea as to how I can repair your implementation. I'll pull this and then make my modifications.

**Pull request merged**
