### PR TITLE
performance micro-optimizations

### PR DESCRIPTION
**Pull request by rhysdh540**
* made some fields final
* simplified some logic in some areas
* used bitwise logic in others
* cached other repeated calculations

I haven't benchmarked this but it probably makes a little difference

### CODE REVIEW

**Comment by Obscure2020** [comment]
Can I ask why you changed the indenting code so dramatically? Please explain exactly what you were trying to improve.

**Comment by rhysdh540** [comment]
I updated it to try to reduce the number of unnecessary calculations it does. In the new implementation:
* If the indent is already correct, it does nothing.
* indent strings that have already been seen are cached.
* Generation of new strings is also sped up (String.repeat isn’t exactly fast)

While this isn’t necessarily hot code, it might help speed things up marginally.

**Comment by Obscure2020** [comment]
I disagree with modifying this portion of code as heavily as you did, in particular because it is very much _**not**_ hot code, as you said. I would like you to add a new commit, making the following changes:

- Remove indent caching.
- Remove "if the indent is already correct, it does nothing." That sort of check would only be applicable if `updateIndent()` were `public`. It's not. It's `private`, and it's only called by `moreIndent()` and `lessIndent()`. This means that almost every time `updateIndent()` is called, it actually *will* need to update the `indent` string.
    - The only cases in which `updateIndent()` is called and will end up leaving `indent` unchanged are when a silly programmer spams `moreIndent()` or `lessIndent()` and starts hitting the bounds of the non-negative `int` range.
- Add a new `private final String indentStr` field to the `PrintSVG` class.
    - Also add a new argument to the `PrintSVG` constructor to pass in a value that will get stored in `indentStr`. For the time being, also hard-code `main()` to pass in `"    "` (four spaces).
- Have `updateIndent()` store `indentStr.repeat(indentAmount)` instead of `" ".repeat(indentAmount * 4)`

I am requesting these changes so that the code realigns with an unstated but pending purpose: once I create a basic GUI for using PixelTrace as a tool, I want to make the indent type settable. I'm likely gonna offer a couple different options via a drop-down, including Four Spaces, Two Spaces, Tabs, and None.

**Review by Obscure2020 — CHANGES_REQUESTED** [review]
Everything remaining looks good, with one exception. Your introduction of the `deltaX` and `deltaY` code inside `Island.pathTrace()` is unnecessary. In those specific locations, neither `detlaX` or `deltaY` will ever be 0, so the check is useless. Put those lines back to how I left them.

**Review by Obscure2020 — APPROVED** [review]
Thanks for fixing this up. I'm gonna merge this PR, and then make a couple adjustments inspired by your changes.

**Pull request merged**
